{% set version = "2.18" %}

package:
  name: pymodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymodes/pymodes-{{ version }}.tar.gz
  sha256: 35829fb52a749cc4b4c1eb95a839073884a215e88f4e8bf8bb5e9d8244c094be

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - poetry-core >=1.3.1
    - cython >=0.29.32
    - pip
  run:
    - python
    - numpy >=1.24.0,<2.0.0
    - pyzmq >=24.0.0,<25.0.0

test:
  imports:
    - pyModeS
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/junzis/pyModeS
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python decoder for Mode S and ADS-B signals

extra:
  recipe-maintainers:
    - junzis
    - xoolive
