{% set version = "2.15" %}

package:
  name: pymodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymodes/pymodes-{{ version }}.tar.gz
  sha256: e5887351e0509a24686caec4a13f202b67ea6d672aaf61e9a6c7f38bc5e4411d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - Cython
    - poetry >=1.3.1
    - poetry-core
  run:
    - python
    - numpy
    - pyzmq

test:
  imports:
    - pyModeS

about:
  home: https://github.com/junzis/pyModeS
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python decoder for Mode S and ADS-B signals

extra:
  recipe-maintainers:
    - junzis
    - xoolive
