{% set version = "2.9" %}

package:
  name: pymodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymodes/pyModeS-{{ version }}.tar.gz
  sha256: df55e0812fb5985ac9004b2607f4861ecba7e803561282dba58f07215acc4d92

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - Cython
  run:
    - python
    - numpy
    - pyzmq

test:
  imports:
    - pyModeS

about:
  home: https://github.com/junzis/pyModeS
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python decoder for Mode S and ADS-B signals

extra:
  recipe-maintainers:
    - junzis
    - xoolive
