{% set version = "2.14" %}

package:
  name: pymodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymodes/pyModeS-{{ version }}.tar.gz
  sha256: 392b19a17c592bd06f79c3d87d55f0c5cba1adf84ee0c3a493468f3e98fef0d9

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - poetry >=1.3.1
    - poetry-core
  host:
    - python >=3.8,<4.0
    - pip
    - Cython
  run:
    - python >=3.8,<4.0
    - numpy >=1.24
    - pyzmq

test:
  imports:
    - pyModeS

about:
  home: https://github.com/junzis/pyModeS
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python decoder for Mode S and ADS-B signals

extra:
  recipe-maintainers:
    - junzis
    - xoolive
